# Generated by Django 4.1.2 on 2023-02-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dent_site', '0002_h1_delete_h2_delete_h3_delete_menu_delete_news_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='H1',
            new_name='Menu',
        ),
    ]
