# Generated by Django 4.1.2 on 2023-03-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent_site', '0004_h2_h3_news_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AddField(
            model_name='h3',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='h3',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
