# Generated by Django 4.2.1 on 2023-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent_site', '0005_delete_text_h3_image_h3_text_alter_news_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='H2',
        ),
        migrations.DeleteModel(
            name='H3',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(),
        ),
    ]
