# Generated by Django 4.2.1 on 2023-07-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent_site', '0006_delete_h2_delete_h3_delete_menu_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
